name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Деплой при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build static assets with PostCSS
      run: |
        npx postcss theme/main.css -o theme/main.min.css --verbose

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs
      run: |
        pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

    - name: Validate HTML
      run: |
        npm install -g html-validator-cli
        html-validator --file=site/index.html --verbose
    
    - name: Validate CSS
      run: |
        npx stylelint "theme/*.css"